library(readxl)
library(writexl)
library(dplyr)
library(tibble)
library(purrr)
library(stringr)
library(cluster)
library(ape)
library(geometry)
library(vegan)

# ==============================================================================
# 1. Global Configurations
# ==============================================================================

raw_data_path <- file.path("..", "000_input_file", "raw_data") 
# The input folder "raw_data" contains dataset-specific Excel files.
#
# Due to data protection agreements and restrictions, the raw_data folder 
# cannot be shared publicly. This raw-data processing section is retained 
# to document the full computational workflow used to generate trait_summary_by_dataset.xlsx.
#
# Fig. 5 is plotted using the processed file trait_summary_by_dataset.xlsx
# generated by this section. To reproduce Fig. 5, please skip below 
# "Plot Fig5" section.

mapping_file  <- file.path("..", "000_input_file", "trait_mapping.xlsx")

output_file <- file.path("..", "000_output_file", "summary_by_dataset.xlsx")
dir.create(dirname(output_file), showWarnings = FALSE, recursive = TRUE)

n_iter     <- 1000
n_axes_max <- 4
n_mc       <- 10000

set.seed(321)

# Load and clean trait mapping table
trait_map <- read_excel(mapping_file) %>% 
  mutate(across(everything(), ~str_trim(as.character(.))))

# Define functional dimensions
broad_dims <- list(
  Size     = c("Size"),
  Resource = c("Resource_acquisition", "Feeding", "Trophic", "Trophic_strategy"),
  Habitat  = c("Habitat", "Life_form", "Attachment", "Guild", "Habit", "Buoyancy")
)

# Identify organism type based on filename code
get_organism <- function(f) {
  code <- substr(tools::file_path_sans_ext(basename(f)), 4, 5)
  case_when(
    code == "BD" ~ "Diatoms",
    code == "BM" ~ "Macroinvertebrates",
    code == "FI" ~ "Fish",
    code == "PP" ~ "Phytoplankton",
    code == "ZP" ~ "Zooplankton",
    code == "AP" ~ "Aquatic plants",
    TRUE ~ "Others"
  )
}

# ==============================================================================
# 2. Geometric Calculation Functions
# ==============================================================================

# Calculate Convex Hull Volume
get_hull <- function(sp, trait_space) {
  pts <- trait_space[rownames(trait_space) %in% sp, , drop = FALSE] %>% 
    na.omit() %>% 
    unique()
  
  d <- ncol(pts)
  # Points must be > dimensions + 1 for a valid volume
  if (nrow(pts) < d + 1) return(NULL)
  
  hull <- tryCatch(
    convhulln(as.matrix(pts), options = "FA"),
    error = function(e) NULL
  )
  
  if (is.null(hull)) return(NULL)
  
  list(hull = hull, vol = hull$vol, pts = as.matrix(pts))
}

# Calculate Intersection Volume using Monte Carlo Integration
calc_overlap <- function(h1, h2, n_points = 10000) {
  all_pts <- rbind(h1$pts, h2$pts)
  d <- ncol(all_pts)
  
  b_min <- apply(all_pts, 2, min)
  b_max <- apply(all_pts, 2, max)
  b_vol <- prod(b_max - b_min)
  
  if(b_vol <= 0) return(0)
  
  rand_pts <- matrix(runif(n_points * d), n_points, d) %>% 
    sweep(2, b_max - b_min, "*") %>% 
    sweep(2, b_min, "+")
  
  in1 <- tryCatch(inhulln(h1$hull, rand_pts), error = function(e) rep(FALSE, n_points))
  in2 <- tryCatch(inhulln(h2$hull, rand_pts), error = function(e) rep(FALSE, n_points))
  
  inter_vol <- b_vol * mean(in1 & in2, na.rm = TRUE)
  return(min(inter_vol, h1$vol, h2$vol))
}

# ==============================================================================
# 3. Core Processing Function
# ==============================================================================

process_dataset_by_dim <- function(f) {
  d_name <- tools::file_path_sans_ext(basename(f))
  org    <- get_organism(f)
  message(">>> Processing: ", d_name, " (", org, ")")
  
  # Read Data
  abu <- read_excel(f, "species")
  tra <- read_excel(f, "traits")
  env <- read_excel(f, "environment")
  
  colnames(abu)[1] <- "Site"
  colnames(env)[1] <- "Site"
  colnames(tra)[1] <- "Species"
  
  # Site selection and TP grouping (Top/Mid/Bottom 20% or 25%)
  richness <- tibble(Site = as.character(abu$Site), S = rowSums(abu[, -1] > 0, na.rm = TRUE))
  env_clean <- env %>% 
    mutate(Site = as.character(Site), TP = as.numeric(TP)) %>% 
    filter(Site %in% richness$Site[richness$S >= 3], !is.na(TP))
  
  if (nrow(env_clean) < 15) return(NULL)
  
  n_e <- floor(nrow(env_clean) * 0.20)
  if (n_e < 2) return(NULL)
  
  env_ordered <- env_clean %>% arrange(TP)
  n_total     <- nrow(env_ordered)
  
  low_sites  <- env_ordered$Site[1:n_e]
  high_sites <- env_ordered$Site[(n_total - n_e + 1):n_total]
  mid_start  <- floor((n_total - n_e) / 2) + 1
  mid_sites  <- env_ordered$Site[mid_start:(mid_start + n_e - 1)]
  
  tp_gps <- bind_rows(
    tibble(Site = low_sites,  gp = "low"),
    tibble(Site = mid_sites,  gp = "mid"),
    tibble(Site = high_sites, gp = "high")
  )
  
  # Presence-Absence Community Matrix
  comm <- abu %>% filter(Site %in% tp_gps$Site) %>% column_to_rownames("Site") %>% decostand("pa")
  org_map <- trait_map %>% filter(Organism == org)
  
  # Loop through Dimensions
  map_dfr(names(broad_dims), function(dim_name) {
    target_traits <- org_map %>% filter(Trait_category %in% broad_dims[[dim_name]]) %>% pull(Original_trait)
    
    # Exact column matching
    actual_cols <- colnames(tra)[unlist(map(target_traits, ~ which(str_detect(colnames(tra), paste0("^", .x, "$")))))]
    actual_cols <- unique(actual_cols)
    
    if (length(actual_cols) < 1) return(NULL)
    
    # Robust Cleaning: Handling data types and missing values
    tra_sub <- tra %>% 
      select(Species, all_of(actual_cols)) %>% 
      filter(!is.na(Species)) %>%
      mutate(across(all_of(actual_cols), ~ as.numeric(as.character(.)))) %>% 
      na.omit() %>%
      distinct(Species, .keep_all = TRUE) %>% 
      column_to_rownames("Species")
    
    # Remove columns with zero variance
    tra_sub <- tra_sub[, apply(tra_sub, 2, function(x) sd(x, na.rm=TRUE)) > 0, drop=FALSE]
    
    if (nrow(tra_sub) < 5 || ncol(tra_sub) < 1) return(NULL)
    
    # Construct PCoA Space
    dist_m <- daisy(tra_sub, metric = "gower")
    pcoa_res <- tryCatch(pcoa(dist_m, correction = "cailliez"), error = function(e) NULL)
    if (is.null(pcoa_res)) return(NULL)
    
    n_ax <- min(n_axes_max, sum(pcoa_res$values$Eigenvalues > 0.0001), nrow(tra_sub) - 1)
    if (n_ax < 2) return(NULL)
    
    trait_space <- as.data.frame(pcoa_res$vectors[, 1:n_ax, drop = FALSE])
    
    # Bootstrap iteration
    map_dfr(1:n_iter, function(i) {
      get_sp <- function(target_gp) {
        target_sites <- tp_gps$Site[tp_gps$gp == target_gp]
        s_sites <- sample(target_sites, length(target_sites), replace = TRUE)
        present <- colSums(comm[rownames(comm) %in% s_sites, colnames(comm) %in% rownames(tra_sub), drop=FALSE]) > 0
        names(present)[present]
      }
      
      s_l <- get_sp("low"); s_m <- get_sp("mid"); s_h <- get_sp("high")
      pairs <- list(lm = list(s_l, s_m), mh = list(s_m, s_h), lh = list(s_l, s_h))
      
      map_dfr(names(pairs), function(p_name) {
        h1 <- get_hull(pairs[[p_name]][[1]], trait_space)
        h2 <- get_hull(pairs[[p_name]][[2]], trait_space)
        if (is.null(h1) || is.null(h2)) return(NULL)
        
        v_i <- calc_overlap(h1, h2, n_mc)
        tibble(Comparison = p_name, Loss = (h1$vol - v_i)/h1$vol, Gain = (h2$vol - v_i)/h2$vol)
      })
    }) %>% mutate(Dimension = dim_name)
  }) %>% mutate(Dataset = d_name, Organism = org)
}

# ==============================================================================
# 4. Loop Execution
# ==============================================================================

files <- list.files(raw_data_path, "\\.xlsx$", full.names = TRUE)
files <- files[!grepl("^~\\$", basename(files))]

all_dim_results <- map_dfr(files, ~ {
  tryCatch(process_dataset_by_dim(.x), error = function(e) {
    message("!!! Error in file: ", basename(.x), " -> ", e$message)
    return(NULL)
  })
})

# ==============================================================================
# 5. Summary only, no plotting
# ==============================================================================

if (nrow(all_dim_results) > 0) {
  
  # Summary by Dataset
  summary_by_dataset <- all_dim_results %>%
    group_by(Dataset, Dimension, Comparison, Organism) %>%
    summarise(Net_change = mean(Gain - Loss, na.rm = TRUE), .groups = "drop") %>%
    mutate(Comparison = factor(Comparison, 
                               levels = c("lm", "mh", "lh"), 
                               labels = c("Low-Mid", "Mid-High", "Low-High")))
  
} else {
  message("No valid data.")
}

write_xlsx(
  trait_summary_by_dataset,
  output_file
)



#### Plot Fig5
# ==============================================================================
# 1. Read trait_summary_by_dataset
# ==============================================================================
summary_by_dataset <- read_excel(file.path("..", "000_input_file", "trait_summary_by_dataset.xlsx")) %>%
  mutate(
    Dimension = factor(Dimension, levels = c("Habitat", "Resource", "Size")),
    Comparison = factor(
      Comparison,
      levels = c("Low-Mid", "Mid-High", "Low-High")
    )
  )

# ==============================================================================
# 2. Calculate global statistics
# ==============================================================================

summary_stats <- summary_by_dataset %>%
  group_by(Dimension, Comparison) %>%
  summarise(
    Mean_net = mean(Net_change, na.rm = TRUE),
    se_net   = sd(Net_change, na.rm = TRUE) / sqrt(n()),
    n        = n(),
    .groups  = "drop"
  )



pd <- position_dodge(width = 0.45)

my_cols <- c(
  Habitat  = "#1B9E77",
  Resource = "#E67E22",
  Size     = "#7FB3D5"
)

p <- ggplot(summary_stats, aes(x = Comparison, y = Mean_net, color = Dimension)) +
  geom_hline(
    yintercept = 0,
    linetype = "dashed",
    color = "grey60",
    linewidth = 0.6
  ) +
  geom_linerange(
    aes(ymin = Mean_net - se_net, ymax = Mean_net + se_net),
    linewidth = 0.9,
    position = pd
  ) +
  geom_point(
    size = 3.6,
    position = pd
  ) +
  scale_color_manual(values = my_cols) +
  coord_cartesian(ylim = c(-0.15, 0.15)) +
  labs(
    x = NULL,
    y = "Functional net change (Gain - Loss)",
    color = "Trait dimension"
  ) +
  theme_bw(base_size = 14) +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(color = "grey90", linewidth = 0.4),
    axis.text.x = element_text(angle = 30, hjust = 1),
    axis.text.y = element_text(color = "black"),
    axis.title.y = element_text(size = 12),
    legend.title = element_text(),
    legend.text = element_text(),
    legend.position = "top",
    legend.background = element_blank(),
    panel.border = element_rect(color = "black", linewidth = 0.8),
    plot.margin = margin(10, 12, 10, 10)
  )

p
